---
## Re start search engine application from remote.

- hosts: all
  user: root
  connection: ssh

  tasks:
    - name: Re start search engine.
      shell: /home/searcher/ops/restart.sh >> /tmp/search_engine_restart_result
